// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6f86pHLu3R1QGoK4DUe0A3ipTnmhDFc4',
    appId: '1:408754876929:android:78135e407aec8cc17a0600',
    messagingSenderId: '408754876929',
    projectId: 'farmers-guide-3e490',
    storageBucket: 'farmers-guide-3e490.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpK90SG9jYAKF0DudoQrQzIhfge-QcGcs',
    appId: '1:408754876929:ios:59bcdfd4d3d7e71d7a0600',
    messagingSenderId: '408754876929',
    projectId: 'farmers-guide-3e490',
    storageBucket: 'farmers-guide-3e490.firebasestorage.app',
    androidClientId: '408754876929-nbijlob7u5f6qmr8dc2klgekf4ghchif.apps.googleusercontent.com',
    iosClientId: '408754876929-csjlsclvjutancg67bnihcmh204mh0kq.apps.googleusercontent.com',
    iosBundleId: 'com.example.agromate',
  );

}